source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VizFig_Example' do
  platform :ios, '8.0'
  pod "VizFig", :path => "../"
end

target 'VizFig_Tests' do 
  platform :ios, '8.0'
  pod "VizFig", :path => "../"

target 'VizFigExampleOSX' do
  platform :osx, '10.10'
  pod "VizFig", :path => "../"
end
  
end
