//
// Generated by VizFig available at https://github.com/OakCityLabs/VizFig
// Generated on 08/12/2015 at 10:52 AM based on class attributes of the 'Configuration' class.

import VizFig

class MagicView: BaseConfigView {
    @IBOutlet var fonterizeBoringFont: [NSView]? { 
        didSet { 
            fonterize(Configuration.boringFont, items: fonterizeBoringFont)
        } 
    }

    @IBOutlet var fonterizeMacFont: [NSView]? { 
        didSet { 
            fonterize(Configuration.macFont, items: fonterizeMacFont)
        } 
    }

    @IBOutlet var colorizeRedColor: [NSView]? { 
        didSet { 
            colorize(Configuration.redColor, items: colorizeRedColor)
        } 
    }

    @IBOutlet var colorizeBlueColor: [NSView]? { 
        didSet { 
            colorize(Configuration.blueColor, items: colorizeBlueColor)
        } 
    }

    @IBOutlet var bgColorizeRedColor: [NSView]? { 
        didSet { 
            bgColorize(Configuration.redColor, items: bgColorizeRedColor)
        } 
    }

    @IBOutlet var bgColorizeBlueColor: [NSView]? { 
        didSet { 
            bgColorize(Configuration.blueColor, items: bgColorizeBlueColor)
        } 
    }

    @IBOutlet var stringifyCatchPhraseString: [NSView]? { 
        didSet { 
            stringify(Configuration.catchPhraseString, items: stringifyCatchPhraseString)
        } 
    }

}
